enum ActionType {
  SET_PERSONAL_ROOM = 'racingSetPersonalRoom',
  LOAD_CURRENT_ROOM = 'racingLoadCurrentRoom',
  SET_CURRENT_ROOM = 'racingSetCurrentRoom',
  LOAD_AVAILABLE_ROOMS = 'racingLoadAvailableRooms',
  ADD_ROOM_TO_AVAILABLE_ROOMS = 'racingAddRoomToAvailableRooms',
  REMOVE_ROOM_FROM_AVAILABLE_ROOMS = 'racingRemoveRoomFromAvailableRooms',
  LOAD_SHARE_ROOM_URL = 'racingLoadShareRoomUrl',
  RESET_SHARE_ROOM_URL = 'racingResetShareRoomUrl',
  CREATE_ROOM = 'racingCreateRoom',
  SEND_ROOM_URL_TO_EMAILS = 'racingSendRoomUrlToEmails',
  SET_COMMENTATOR_TEXT = 'racingSetCommentatorText',
  ADD_PARTICIPANT = 'racingAddParticipant',
  REMOVE_PARTICIPANT = 'racingRemoveParticipant',
  ADD_LESSON_ID = 'racingAddLessonId',
  REMOVE_LESSON_ID = 'racingRemoveLessonId',
  RESET_IS_LOAD_CURRENT_ROOM_FAILED = 'racingResetIsLoadCurrentRoomFailed',
  TOGGLE_IS_GAME_STARTED = 'racingToggleIsGameStarted',
  TOGGLE_PARTICIPANT_IS_READY = 'racingToggleParticipantIsReady',
  INCREASE_PARTICIPANT_POSITION = 'racingIncreaseParticipantPosition',
  SET_SPENT_TIME = 'racingSetSpentTime',
  INCREASE_CURRENT_PARTICIPANT_POSITION = 'racingIncreaseCurrentParticipantPosition',
  TOGGLE_CURRENT_PARTICIPANT_IS_READY = 'racingToggleCurrentParticipantIsReady',
  RESET_ALL = 'racingResetAll',
  RESET_ALL_EXCEPT_PERSONAL = 'racingResetAllExceptPersonal',
  RESET_AVAILABLE_ROOMS = 'racingResetResetAvailableRooms',
  RESET_CURRENT_ROOM_TO_DEFAULT = 'racingResetCurrentRoomToDefault',
  JOIN_ROOM = 'racingJoinRoom',
  LEAVE_ROOM = 'racingLeaveRoom',
}

export { ActionType };
